### ISSUE TITLE
Auto scroll to the last element when RecyclerView dataset is updated

### ISSUE THREAD

**Issue by martianworm17** [martianworm17/android-one#5]

**Comment by martianworm17** [comment]
Good read.

https://stackoverflow.com/questions/47758084/recyclerview-scrolls-to-bottom-when-data-is-loaded

**Comment by martianworm17** [comment]
Add `smoothScrollToPosition()` or `scrollToPosition()`.

**Comment by martianworm17** [comment]
In my case: `recyclerView.smoothScrollToPosition(myDataset.size());`

**Comment by leiurus17** [comment]
I found the answer here:

https://stackoverflow.com/questions/26580723/how-to-scroll-to-the-bottom-of-a-recyclerview-scrolltoposition-doesnt-work

This issue is fixed. Closing the issue.
